/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ControlsXd92j7kAuthRouteImport } from './routes/controls/xd92j7k/_auth'
import { Route as ApiPublicLoyverseWebhookRouteImport } from './routes/api/public/loyverse-webhook'
import { Route as ControlsXd92j7kAuthIndexRouteImport } from './routes/controls/xd92j7k/_auth.index'
import { Route as ControlsXd92j7kAuthSettingsRouteImport } from './routes/controls/xd92j7k/_auth.settings'

const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsXd92j7kAuthRoute = ControlsXd92j7kAuthRouteImport.update({
  id: '/controls/xd92j7k/_auth',
  path: '/controls/xd92j7k',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLoyverseWebhookRoute =
  ApiPublicLoyverseWebhookRouteImport.update({
    id: '/api/public/loyverse-webhook',
    path: '/api/public/loyverse-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ControlsXd92j7kAuthIndexRoute =
  ControlsXd92j7kAuthIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ControlsXd92j7kAuthRoute,
  } as any)
const ControlsXd92j7kAuthSettingsRoute =
  ControlsXd92j7kAuthSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ControlsXd92j7kAuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/owner': typeof OwnerRoute
  '/api/public/loyverse-webhook': typeof ApiPublicLoyverseWebhookRoute
  '/controls/xd92j7k': typeof ControlsXd92j7kAuthRouteWithChildren
  '/controls/xd92j7k/settings': typeof ControlsXd92j7kAuthSettingsRoute
  '/controls/xd92j7k/': typeof ControlsXd92j7kAuthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/owner': typeof OwnerRoute
  '/api/public/loyverse-webhook': typeof ApiPublicLoyverseWebhookRoute
  '/controls/xd92j7k/settings': typeof ControlsXd92j7kAuthSettingsRoute
  '/controls/xd92j7k': typeof ControlsXd92j7kAuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/owner': typeof OwnerRoute
  '/api/public/loyverse-webhook': typeof ApiPublicLoyverseWebhookRoute
  '/controls/xd92j7k/_auth': typeof ControlsXd92j7kAuthRouteWithChildren
  '/controls/xd92j7k/_auth/settings': typeof ControlsXd92j7kAuthSettingsRoute
  '/controls/xd92j7k/_auth/': typeof ControlsXd92j7kAuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/menu'
    | '/owner'
    | '/api/public/loyverse-webhook'
    | '/controls/xd92j7k'
    | '/controls/xd92j7k/settings'
    | '/controls/xd92j7k/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/menu'
    | '/owner'
    | '/api/public/loyverse-webhook'
    | '/controls/xd92j7k/settings'
    | '/controls/xd92j7k'
  id:
    | '__root__'
    | '/'
    | '/menu'
    | '/owner'
    | '/api/public/loyverse-webhook'
    | '/controls/xd92j7k/_auth'
    | '/controls/xd92j7k/_auth/settings'
    | '/controls/xd92j7k/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MenuRoute: typeof MenuRoute
  OwnerRoute: typeof OwnerRoute
  ApiPublicLoyverseWebhookRoute: typeof ApiPublicLoyverseWebhookRoute
  ControlsXd92j7kAuthRoute: typeof ControlsXd92j7kAuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls/xd92j7k/_auth': {
      id: '/controls/xd92j7k/_auth'
      path: '/controls/xd92j7k'
      fullPath: '/controls/xd92j7k'
      preLoaderRoute: typeof ControlsXd92j7kAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/loyverse-webhook': {
      id: '/api/public/loyverse-webhook'
      path: '/api/public/loyverse-webhook'
      fullPath: '/api/public/loyverse-webhook'
      preLoaderRoute: typeof ApiPublicLoyverseWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls/xd92j7k/_auth/': {
      id: '/controls/xd92j7k/_auth/'
      path: '/'
      fullPath: '/controls/xd92j7k/'
      preLoaderRoute: typeof ControlsXd92j7kAuthIndexRouteImport
      parentRoute: typeof ControlsXd92j7kAuthRoute
    }
    '/controls/xd92j7k/_auth/settings': {
      id: '/controls/xd92j7k/_auth/settings'
      path: '/settings'
      fullPath: '/controls/xd92j7k/settings'
      preLoaderRoute: typeof ControlsXd92j7kAuthSettingsRouteImport
      parentRoute: typeof ControlsXd92j7kAuthRoute
    }
  }
}

interface ControlsXd92j7kAuthRouteChildren {
  ControlsXd92j7kAuthSettingsRoute: typeof ControlsXd92j7kAuthSettingsRoute
  ControlsXd92j7kAuthIndexRoute: typeof ControlsXd92j7kAuthIndexRoute
}

const ControlsXd92j7kAuthRouteChildren: ControlsXd92j7kAuthRouteChildren = {
  ControlsXd92j7kAuthSettingsRoute: ControlsXd92j7kAuthSettingsRoute,
  ControlsXd92j7kAuthIndexRoute: ControlsXd92j7kAuthIndexRoute,
}

const ControlsXd92j7kAuthRouteWithChildren =
  ControlsXd92j7kAuthRoute._addFileChildren(ControlsXd92j7kAuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MenuRoute: MenuRoute,
  OwnerRoute: OwnerRoute,
  ApiPublicLoyverseWebhookRoute: ApiPublicLoyverseWebhookRoute,
  ControlsXd92j7kAuthRoute: ControlsXd92j7kAuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
