/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ControlsXd92j7kAuthRouteImport } from './routes/controls/xd92j7k/_auth'
import { Route as ApiPublicPlaceOrderRouteImport } from './routes/api/public/place-order'
import { Route as ApiPublicPlaceBookingRouteImport } from './routes/api/public/place-booking'
import { Route as ControlsXd92j7kAuthIndexRouteImport } from './routes/controls/xd92j7k/_auth.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ControlsXd92j7kAuthSettingsRouteImport } from './routes/controls/xd92j7k/_auth.settings'
import { Route as ControlsXd92j7kAuthKitchenRouteImport } from './routes/controls/xd92j7k/_auth.kitchen'
import { Route as ControlsXd92j7kAuthBookingsRouteImport } from './routes/controls/xd92j7k/_auth.bookings'
import { Route as ApiPublicHooksDailyDigestRouteImport } from './routes/api/public/hooks/daily-digest'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsXd92j7kAuthRoute = ControlsXd92j7kAuthRouteImport.update({
  id: '/controls/xd92j7k/_auth',
  path: '/controls/xd92j7k',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlaceOrderRoute = ApiPublicPlaceOrderRouteImport.update({
  id: '/api/public/place-order',
  path: '/api/public/place-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlaceBookingRoute = ApiPublicPlaceBookingRouteImport.update({
  id: '/api/public/place-booking',
  path: '/api/public/place-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsXd92j7kAuthIndexRoute =
  ControlsXd92j7kAuthIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ControlsXd92j7kAuthRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsXd92j7kAuthSettingsRoute =
  ControlsXd92j7kAuthSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ControlsXd92j7kAuthRoute,
  } as any)
const ControlsXd92j7kAuthKitchenRoute =
  ControlsXd92j7kAuthKitchenRouteImport.update({
    id: '/kitchen',
    path: '/kitchen',
    getParentRoute: () => ControlsXd92j7kAuthRoute,
  } as any)
const ControlsXd92j7kAuthBookingsRoute =
  ControlsXd92j7kAuthBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => ControlsXd92j7kAuthRoute,
  } as any)
const ApiPublicHooksDailyDigestRoute =
  ApiPublicHooksDailyDigestRouteImport.update({
    id: '/api/public/hooks/daily-digest',
    path: '/api/public/hooks/daily-digest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/menu': typeof MenuRoute
  '/owner': typeof OwnerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/place-booking': typeof ApiPublicPlaceBookingRoute
  '/api/public/place-order': typeof ApiPublicPlaceOrderRoute
  '/controls/xd92j7k': typeof ControlsXd92j7kAuthRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRoute
  '/controls/xd92j7k/bookings': typeof ControlsXd92j7kAuthBookingsRoute
  '/controls/xd92j7k/kitchen': typeof ControlsXd92j7kAuthKitchenRoute
  '/controls/xd92j7k/settings': typeof ControlsXd92j7kAuthSettingsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/controls/xd92j7k/': typeof ControlsXd92j7kAuthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/menu': typeof MenuRoute
  '/owner': typeof OwnerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/place-booking': typeof ApiPublicPlaceBookingRoute
  '/api/public/place-order': typeof ApiPublicPlaceOrderRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRoute
  '/controls/xd92j7k/bookings': typeof ControlsXd92j7kAuthBookingsRoute
  '/controls/xd92j7k/kitchen': typeof ControlsXd92j7kAuthKitchenRoute
  '/controls/xd92j7k/settings': typeof ControlsXd92j7kAuthSettingsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/controls/xd92j7k': typeof ControlsXd92j7kAuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/menu': typeof MenuRoute
  '/owner': typeof OwnerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/place-booking': typeof ApiPublicPlaceBookingRoute
  '/api/public/place-order': typeof ApiPublicPlaceOrderRoute
  '/controls/xd92j7k/_auth': typeof ControlsXd92j7kAuthRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRoute
  '/controls/xd92j7k/_auth/bookings': typeof ControlsXd92j7kAuthBookingsRoute
  '/controls/xd92j7k/_auth/kitchen': typeof ControlsXd92j7kAuthKitchenRoute
  '/controls/xd92j7k/_auth/settings': typeof ControlsXd92j7kAuthSettingsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/controls/xd92j7k/_auth/': typeof ControlsXd92j7kAuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/menu'
    | '/owner'
    | '/reset-password'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/api/public/place-booking'
    | '/api/public/place-order'
    | '/controls/xd92j7k'
    | '/lovable/email/suppression'
    | '/api/public/hooks/daily-digest'
    | '/controls/xd92j7k/bookings'
    | '/controls/xd92j7k/kitchen'
    | '/controls/xd92j7k/settings'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/controls/xd92j7k/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/menu'
    | '/owner'
    | '/reset-password'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/api/public/place-booking'
    | '/api/public/place-order'
    | '/lovable/email/suppression'
    | '/api/public/hooks/daily-digest'
    | '/controls/xd92j7k/bookings'
    | '/controls/xd92j7k/kitchen'
    | '/controls/xd92j7k/settings'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/controls/xd92j7k'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/menu'
    | '/owner'
    | '/reset-password'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/api/public/place-booking'
    | '/api/public/place-order'
    | '/controls/xd92j7k/_auth'
    | '/lovable/email/suppression'
    | '/api/public/hooks/daily-digest'
    | '/controls/xd92j7k/_auth/bookings'
    | '/controls/xd92j7k/_auth/kitchen'
    | '/controls/xd92j7k/_auth/settings'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/controls/xd92j7k/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  MenuRoute: typeof MenuRoute
  OwnerRoute: typeof OwnerRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicPlaceBookingRoute: typeof ApiPublicPlaceBookingRoute
  ApiPublicPlaceOrderRoute: typeof ApiPublicPlaceOrderRoute
  ControlsXd92j7kAuthRoute: typeof ControlsXd92j7kAuthRouteWithChildren
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksDailyDigestRoute: typeof ApiPublicHooksDailyDigestRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls/xd92j7k/_auth': {
      id: '/controls/xd92j7k/_auth'
      path: '/controls/xd92j7k'
      fullPath: '/controls/xd92j7k'
      preLoaderRoute: typeof ControlsXd92j7kAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/place-order': {
      id: '/api/public/place-order'
      path: '/api/public/place-order'
      fullPath: '/api/public/place-order'
      preLoaderRoute: typeof ApiPublicPlaceOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/place-booking': {
      id: '/api/public/place-booking'
      path: '/api/public/place-booking'
      fullPath: '/api/public/place-booking'
      preLoaderRoute: typeof ApiPublicPlaceBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls/xd92j7k/_auth/': {
      id: '/controls/xd92j7k/_auth/'
      path: '/'
      fullPath: '/controls/xd92j7k/'
      preLoaderRoute: typeof ControlsXd92j7kAuthIndexRouteImport
      parentRoute: typeof ControlsXd92j7kAuthRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls/xd92j7k/_auth/settings': {
      id: '/controls/xd92j7k/_auth/settings'
      path: '/settings'
      fullPath: '/controls/xd92j7k/settings'
      preLoaderRoute: typeof ControlsXd92j7kAuthSettingsRouteImport
      parentRoute: typeof ControlsXd92j7kAuthRoute
    }
    '/controls/xd92j7k/_auth/kitchen': {
      id: '/controls/xd92j7k/_auth/kitchen'
      path: '/kitchen'
      fullPath: '/controls/xd92j7k/kitchen'
      preLoaderRoute: typeof ControlsXd92j7kAuthKitchenRouteImport
      parentRoute: typeof ControlsXd92j7kAuthRoute
    }
    '/controls/xd92j7k/_auth/bookings': {
      id: '/controls/xd92j7k/_auth/bookings'
      path: '/bookings'
      fullPath: '/controls/xd92j7k/bookings'
      preLoaderRoute: typeof ControlsXd92j7kAuthBookingsRouteImport
      parentRoute: typeof ControlsXd92j7kAuthRoute
    }
    '/api/public/hooks/daily-digest': {
      id: '/api/public/hooks/daily-digest'
      path: '/api/public/hooks/daily-digest'
      fullPath: '/api/public/hooks/daily-digest'
      preLoaderRoute: typeof ApiPublicHooksDailyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ControlsXd92j7kAuthRouteChildren {
  ControlsXd92j7kAuthBookingsRoute: typeof ControlsXd92j7kAuthBookingsRoute
  ControlsXd92j7kAuthKitchenRoute: typeof ControlsXd92j7kAuthKitchenRoute
  ControlsXd92j7kAuthSettingsRoute: typeof ControlsXd92j7kAuthSettingsRoute
  ControlsXd92j7kAuthIndexRoute: typeof ControlsXd92j7kAuthIndexRoute
}

const ControlsXd92j7kAuthRouteChildren: ControlsXd92j7kAuthRouteChildren = {
  ControlsXd92j7kAuthBookingsRoute: ControlsXd92j7kAuthBookingsRoute,
  ControlsXd92j7kAuthKitchenRoute: ControlsXd92j7kAuthKitchenRoute,
  ControlsXd92j7kAuthSettingsRoute: ControlsXd92j7kAuthSettingsRoute,
  ControlsXd92j7kAuthIndexRoute: ControlsXd92j7kAuthIndexRoute,
}

const ControlsXd92j7kAuthRouteWithChildren =
  ControlsXd92j7kAuthRoute._addFileChildren(ControlsXd92j7kAuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  MenuRoute: MenuRoute,
  OwnerRoute: OwnerRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicPlaceBookingRoute: ApiPublicPlaceBookingRoute,
  ApiPublicPlaceOrderRoute: ApiPublicPlaceOrderRoute,
  ControlsXd92j7kAuthRoute: ControlsXd92j7kAuthRouteWithChildren,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksDailyDigestRoute: ApiPublicHooksDailyDigestRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
